name: Deploy to Azure App Service (staging)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive application
        run: zip -r app.zip .

      - name: verify Azure Credentials
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "Azure credentials are not set. Please set the AZURE_CREDENTIALS secret.";
          exit 1;
          else
          echo "Azure credentials are set.";
          fi

      - name: Login to Azure
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: staging (fast-api-test/staging)
          slot-name: staging
          package: app.zip
